// Copies the AgentBonds ABI from Foundry build output into src/abi.ts.
// Run after changing the contract: `yarn foundry:compile && yarn workspace @sh/agent sync-abi`.
import { readFileSync, writeFileSync } from "node:fs";
import { dirname, join } from "node:path";
import { fileURLToPath } from "node:url";

const here = dirname(fileURLToPath(import.meta.url));
const artifact = join(here, "..", "..", "foundry", "out", "AgentBonds.sol", "AgentBonds.json");
const { abi } = JSON.parse(readFileSync(artifact, "utf8"));

writeFileSync(
  join(here, "..", "src", "abi.ts"),
  [
    "// Generated by scripts/sync-abi.mjs from packages/foundry/out. Do not edit by hand.",
    `export const agentBondsAbi = ${JSON.stringify(abi, null, 2)} as const;`,
    "",
  ].join("\n\n"),
);
console.log("Wrote src/abi.ts");
